---
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${ACCOUNT_ID}:role/eksctl-quick-eks-addon-iamserviceaccount-api-Role1-xxx"
  name: api-sa
  namespace: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api
  name: deployment-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - image: "$ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/cop301-api"
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8000
          env:
            - name: HOST_IP
              value: 10.100.168.34
              # value: otel.otel-collector.svc.cluster.local # 会有 DNS 解析告警，可以正常推送
              # valueFrom:
              #   fieldRef:
              #     fieldPath: status.hostIP
            - name: DATA_API
              value: "xxx/votes"
            - name: DATA_API_REGION
              value: "us-west-2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: api
  name: service-api
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: api